### ISSUE TITLE
Tabs break if the recipe book is opened

### ISSUE THREAD

**Issue by Foozey** [majikdev/rereskillable#10]
![image](https://user-images.githubusercontent.com/68371808/120992763-403b1d00-c7c6-11eb-9f7a-e4baa00afe69.png)

**Comment by Foozey** [comment]
You might be able to fix this by checking if the recipe book is opened, and if it is, hide the tabs.

**Comment by majikdev** [comment]
That's what I'm trying to do, but can't find a way to check that currently. Will look into this later.

**Comment by majikdev** [comment]
Fixed in 1.3.3
