### ISSUE TITLE
If the maximum level isn't divisible by 4 (the total number of icon tiers), then the icon system breaks

### ISSUE THREAD

**Issue by Foozey** [majikdev/rereskillable#11]
For example, if I set maximum level to 10, it will reach the top tier too early when levelling up. This causes it to think there's supposed to be another tier after it, even though there's not, resulting in a missing icon.

**Comment by majikdev** [comment]
Probably an issue with how I round the numbers, will probably be fixed soon. To clarify, when you set the max level to 10, you never get to the last tier icons?

**Comment by Foozey** [comment]
No, you get to the last tier icons, but you go beyond them. So it basically goes like this:

At tier 1 - 1st set of icons
At tier 2 - 2nd set of icons
At tier 4 - 3rd set of icons
At tier 6 - 4th set of icons
At tier 7 or 8 (i forget lol) - icons are gone all together because it's looking for a tier beyond the max icon tier

**Comment by Foozey** [comment]
And yeah, I'm pretty confident this is an issue with float conversion/rounding.

**Comment by majikdev** [comment]
Ok after doing some math I fixed it, will be out in next release.
