### ISSUE TITLE
Unknown error with agility..?

### ISSUE THREAD

**Issue by thedeerirty** [majikdev/rereskillable#16]
Could you please pinpoint to me what's causing a crash here? I've made sure my .toml file is valid and everything.
[crash-2021-06-18_15.44.40-fml.txt](https://github.com/majikdev/rereskillable/files/6679055/crash-2021-06-18_15.44.40-fml.txt)

**Comment by majikdev** [comment]
Provide the config file please.

**Comment by thedeerirty** [comment]
says github doesn't support .toml
here's a pastebin
https://pastebin.com/NFrZEGJC

the multiple lines are from pastebin; its all one line in my config file

**Comment by majikdev** [comment]
agiliy in "iceandfire:stymphalian_feather_bundle agiliy:6 building:6"

**Comment by thedeerirty** [comment]
ah, agony.
always one little thing
thanks so much for the catch, my bad for buggin' ya
