### ISSUE TITLE
common config on servers doesn't work

### ISSUE THREAD

**Issue by meteorok** [majikdev/rereskillable#20]
Hello, I found that the common configuration for servers doesn't work, instead the showed requirements are the local values from the client side config.

By this way the mod is useless on servers
Can you fix it please :(?

**Comment by IdealIdeas** [comment]
Both the server and client need to have the same config file.

If you have it just on the server, the items should still have their restrictions but the players wont see the changes as the mod refers to the config on the client side and not off the server

**Comment by Kasualix** [comment]
And when my players died in my server, all of their skills were lost.
