### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by akaManifest** [majikdev/rereskillable#24]
How exactly do I use this mod? I'm not exactly knowledgeable when it comes to changing config files and really anything more complicated then just drag and dropping mods. I just need to know exactly where to start and plug in the commands I've seen. I know how the mod works but not how to set it up.

**Comment by Marianz222** [comment]
I recommend you use the mod "Configured" by MrCrayfish, it's a very useful tool for this particular config file. You need to open the mod configuration with this mod installed and use the "Edit" button on the "Skill Locks" section, then you need to add the item you want to lock. For example, my mod has X block and i want to set building:6 as requirement. You need to input there "modid:blockid building:6" and click add. You can do this with pretty much anything that has a right-click functionallity. Hope it helps
