### ISSUE TITLE
[Bug] Clients don't read displays if the config is different from the server's config. Temp fix is to share the server's config.

### ISSUE THREAD

**Issue by Cixon** [majikdev/rereskillable#3]
Mod in experiment is Relics.
Link: https://www.curseforge.com/minecraft/mc-mods/relics-mod

**Example:** _(midnight robe should display require magic 20)_
![Screenshot (254)](https://user-images.githubusercontent.com/69068153/118349690-bcb84400-b517-11eb-80e4-f775915cd788.png)
![Screenshot (255)](https://user-images.githubusercontent.com/69068153/118349692-bde97100-b517-11eb-9e9b-f7efe2e20400.png)

**Comment by Cixon** [comment]
**Additional context:**
Yes, the settings do work over the server. I tried equipping the relic for curios slot and it rejected it but didn't display the requirements.
Using forge v36.1.4.
Using latest rereskillable.

Also, great work on this mod! You're awesome!

**Comment by majikdev** [comment]
Let me clarify. The only thing that doesn't work is the tooltip? Or does the popup also not appear when you try to equip it?

**Comment by Cixon** [comment]
> 
> 
> Let me clarify. The only thing that doesn't work is the tooltip? Or does the popup also not appear when you try to equip it?

Yes, the tooltip as well as the prompt message.

**Comment by majikdev** [comment]
Just checked with Rereskillable 1.2.0, Curios 4.0.5.1 and Relics 0.1.14, everything seems to work.
Are you sure you have the latest versions of all 3 mods and no other mods that could interfere?
![image](https://user-images.githubusercontent.com/45976016/118353326-6cb89c00-b56e-11eb-809d-edc9cdb90b00.png)
![image](https://user-images.githubusercontent.com/45976016/118353406-b73a1880-b56e-11eb-877f-db9bb41b4e0d.png)

**Comment by Cixon** [comment]
I found the issue. It's fairly simple but still a nuisance. Both the client and the server need to have the same exact config in order for the client to get a proper display.

Understandably people with mod-packs most likely won't inhabit this problem but for active server owners where hot-fixes will most likely be needed or when I want to add new restrictions, I'd hate to have to force players to install the new config every time I want to make a change, that's just bizarre.

Perhaps making the config run in real-time or have the server config run totally different than the client by making it a world config or something that would work, that'd be excellent!

**Comment by majikdev** [comment]
Will look into that, thanks!
