### ISSUE TITLE
[Suggestion] Item restrictions apply to offhand slots as well.

### ISSUE THREAD

**Issue by Cixon** [majikdev/rereskillable#4]
**Context:** I'm using the iceandfire mod and I want to add a magic requirement to the cyclops eye. It basically applies the weaken effect to enemies in your radius but in offhand. If you could make it so that restrictions apply to offhand as well that would be great because this can also be used for shields and etc.

**Comment by majikdev** [comment]
The skill locks only work for when you use an item, so right clicking a shield with a skill lock would not work, the same goes for, for example, placing a block with your offhand. About the held items in the offhand, I'd like to let the player hold an item however they want without showing them the unmet requirement popup, so I guess the use of items that give a passive effect when held can't be blocked.

**Comment by Cixon** [comment]
> 
> 
> The skill locks only work for when you use an item, so right clicking a shield with a skill lock would not work, the same goes for, for example, placing a block with your offhand. About the held items in the offhand, I'd like to let the player hold an item however they want without showing them the unmet requirement popup, so I guess the use of items that give a passive effect when held can't be blocked.

Yes so essentially, I don't want users to have the ability to hold the cyclops eye in their offhand as it's a passive effect. Not triggered by any m1 or m2 interaction.
