### ISSUE TITLE
Suggestion: Customization of skills and unlocking recipes

### ISSUE THREAD

**Issue by crafting-Aaron** [majikdev/rereskillable#7]
It would be great having the ability to add custom skills through a configuration file by defining the icon from an item or potion effect and name it. Let's say for example an Alchemy skill:

Icon: "Minecraft:brewing_stand"
Name: "Alchemy"
or
Icon: "minecraft:bow"/"mod:gun" /(Night Vision effect icon)
Name: "Marksmanship"

To add more variety to skills for specific items and concepts from various modpacks.
For recipes, it would be to have an item's recipe locked behind a skill level and will only show up when the requirements are met.

**Comment by majikdev** [comment]
With the way I coded this adding custom skills would be impossible, unless I do a complete rewrite of the whole thing, so sadly I won't be adding custom skill support. For recipes, do you mean not letting the player craft an item which is locked and can't be used by that player? If so, I could probably add that with a config option (by default it will be off).

**Comment by majikdev** [comment]
Oh about the custom skills, there is a messy workaround - You could try to make a resource pack that replaces the icons of skills and their names in the language file. And then add those resources to the modpack with Open Loader or a resource pack.

**Comment by Mig75seo** [comment]
Dear Majikdev,
Can you please tell me which name parameter need to be off ? I have the same issue and can be helpfully to disable it.
Thank you

**Comment by crafting-Aaron** [comment]
> Dear Majikdev, Can you please tell me which name parameter need to be off ? I have the same issue and can be helpfully to disable it. Thank you

Are you trying to change the appearance of skills? What part of the post are you talking about?

**Comment by Mig75seo** [comment]
I refer to this post : 
"With the way I coded this adding custom skills would be impossible, unless I do a complete rewrite of the whole thing, so sadly I won't be adding custom skill support. **For recipes, do you mean not letting the player craft an item which is locked and can't be used by that player? If so, I could probably add that with a config option (by default it will be off)."**

**Comment by crafting-Aaron** [comment]
Ah, I see. So he added it into the mod?
