### ISSUE TITLE
Crash when adding wizard staff from the wizard staff mod

### ISSUE THREAD

**Issue by ekiplier** [majikdev/rereskillable#8]
I get this crash every time I try to add any item from the wizard staff mod to the skillblocks list

![image](https://user-images.githubusercontent.com/74121461/119599977-f4f43800-bddd-11eb-8179-deb28b5369f7.png)

Here's the crash report & logs:
[crash-2021-05-26_04.48.09-fml.txt](https://github.com/majikdev/rereskillable/files/6543722/crash-2021-05-26_04.48.09-fml.txt)
[latest.log](https://github.com/majikdev/rereskillable/files/6543725/latest.log)

**Comment by majikdev** [comment]
Can you please send the configuration file of rereskillable?

**Comment by majikdev** [comment]
You made a mistake in your config file, you used a space instead of a colon between building and the level (should be building:5 and building:10).
```
"minecraft:repeater building 5",
"minecraft:comparator building 10",
```

**Comment by ekiplier** [comment]
Oh lol. Sorry, my bad
